/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Contact.vue')['default']
    Download: typeof import('./src/components/Download.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
    Study: typeof import('./src/components/Study.vue')['default']
  }
}
